language: java
jdk:
  - openjdk11

sudo: false

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      -sidelevcs@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
    - CODECOV_TOKEN="37fd6ba3-7d0b-415a-bee9-9feda01738d7"